//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryCoding.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_message
    {
        public int mId { get; set; }
        public string mMember { get; set; }
        public string mMessage { get; set; }
        [DisplayFormat(DataFormatString ="{0:yyyy/MM/dd HH:mm:ss}")]
        public System.DateTime mTime { get; set; }
    }
}
